plugins {
    id 'java'
    id 'eclipse'
    id 'com.gradleup.shadow' version '9.4.2'
    id 'net.minecraftforge.gradle' version '[7.0.17,8)'
}

eclipse {
    project {
        name = "Dynmap(Forge-1.21.10)"
    }
}

println('Java: ' + System.getProperty('java.version') + ' JVM: ' + System.getProperty('java.vm.version') + '(' + System.getProperty('java.vendor') + ') Arch: ' + System.getProperty('os.arch'))

ext.buildNumber = System.getenv().BUILD_NUMBER ?: "Dev"

repositories {
    minecraft.mavenizer(it)
    maven fg.forgeMaven
    maven fg.minecraftLibsMaven
    mavenCentral()
}

minecraft {
    // Auto-applies src/main/resources/META-INF/accesstransformer.cfg
    accessTransformer = true
}

dependencies {
    implementation minecraft.dependency('net.minecraftforge:forge:1.21.10-60.1.5')
    annotationProcessor 'net.minecraftforge:eventbus-validator:7.0-beta.7'

    implementation project(path: ':DynmapCore', configuration: 'shadow')
    implementation project(path: ':DynmapCoreAPI')
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
    options.release = 21
}

processResources {
    filesMatching('META-INF/mods.toml') {
        // replace version and mcversion
        expand(
            version: project.version + '-' + project.ext.buildNumber,
            mcversion: "1.21.10"
        )
    }
}

shadowJar {
    dependencies {
        include(dependency(':DynmapCore'))
        include(dependency("commons-codec:commons-codec:"))
        exclude("META-INF/maven/**")
        exclude("META-INF/services/**")
    }
    relocate('org.apache.commons.codec', 'org.dynmap.forge_1_21_10.commons.codec')

    archiveBaseName = "Dynmap"
    archiveClassifier = "forge-1.21.10"
    destinationDirectory = file('../target')
}

shadowJar.doLast {
    task ->
        ant.checksum file: task.archiveFile.get().asFile
}

build.dependsOn(shadowJar)
