apply plugin: 'eclipse'

eclipse {
    project {
        name = "Dynmap(dynmap-api)"
    }
}

description = "dynmap-api"

java {
    sourceCompatibility = JavaVersion.VERSION_1_8
    targetCompatibility = JavaVersion.VERSION_1_8
} // Need this here so eclipse task generates correctly.

dependencies {
    compileOnly group: 'org.bukkit', name: 'bukkit', version:'1.7.10-R0.1-SNAPSHOT'
    compileOnly project(":DynmapCoreAPI")
}

jar {
   archiveClassifier  = 'unshaded'
}

shadowJar {
    dependencies {
        include(dependency(":DynmapCoreAPI"))
	}
    destinationDirectory = file '../target'
    archiveClassifier  = ''
}

artifacts {
    archives shadowJar
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            from components.java
        }
    }
}
