modLoader="javafml"
loaderVersion="[4,)"
issueTrackerURL="https://github.com/webbukkit/dynmap/issues"
license="Apache Public License v2"
[[mods]]
modId="dynmap"
version="${version}"
displayName="Dynmap"
authors="mikeprimm"
description='''
Dynamic, Google-maps style rendered maps for your Minecraft server
'''
[[accessTransformers]]
file="META-INF/accesstransformer.cfg"
[[dependencies.dynmap]]
    modId="neoforge"
    mandatory=true
    versionRange="[21.1,)"
    ordering="NONE"
    side="SERVER"
[[dependencies.dynmap]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.21.1,1.22)"
    ordering="NONE"
    side="SERVER"
