plugins {
    id  "com.gradleup.shadow" version "9.4.2"
    id  'java'
    id  'maven-publish'
    id  'io.papermc.paperweight.userdev' version '2.0.0-beta.21' apply false
}

apply plugin: 'eclipse'

eclipse {
    project {
        name = "Dynmap"
    }
}

allprojects  {
  repositories {
     mavenLocal()
     maven { url 'https://libraries.minecraft.net/' }
     maven { url "https://oss.sonatype.org/content/repositories/releases" }
     maven { url "https://oss.sonatype.org/content/repositories/snapshots" }
     maven { url "https://repo.mikeprimm.com" }
     maven { url "https://repo.maven.apache.org/maven2" }
     maven { url "https://hub.spigotmc.org/nexus/content/repositories/snapshots/" }
     maven { url "https://repo.codemc.org/repository/maven-public/" }
  }

  apply plugin: 'java'
  
  group = 'us.dynmap'
  version = '3.9-SNAPSHOT'

}

class Globals {
  String buildNumber =  System.getenv().BUILD_NUMBER ?: "Dev"
}
ext {
  globals = new Globals()
}

subprojects {
  if (!it.name.startsWith('fabric-') && !it.name.startsWith('forge-')) {
    apply plugin: "com.gradleup.shadow"
  }
  apply plugin: 'java'
  apply plugin: 'maven-publish'

  java {
    sourceCompatibility = JavaVersion.VERSION_1_8
    targetCompatibility = JavaVersion.VERSION_1_8
  }
  tasks.withType(JavaCompile) {
  	options.encoding = 'UTF-8'
  }
}

clean {
  delete "target" 
}

task setupCIWorkspace {
}
