eclipse {
    project {
        name = "Dynmap(Spigot-1.21.4)"
    }
}

description = 'bukkit-helper-1.21.4'

java {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
}

dependencies {
  implementation project(':bukkit-helper')
  implementation project(':dynmap-api')
  implementation project(path: ':DynmapCore', configuration: 'shadow')
  compileOnly group: 'org.spigotmc', name: 'spigot-api', version:'1.21.4-R0.1-SNAPSHOT'
  compileOnly ('org.spigotmc:spigot:1.21.4-R0.1-SNAPSHOT') {
    exclude group: "com.mojang", module: "jtracy"
  }
}
