name: dynmap
main: org.dynmap.DynmapPlugin
version: "0.21"
authors: [FrozenCow, mikeprimm, zeeZ]
softdepend: [Permissions]
commands:
  dynmap:
    description: Controls Dynmap.
    usage: |
           /<command> hide - hides the player from the map.
           /<command> hide TheDude - hides the player 'TheDude' from the map.
           /<command> show - shows the player from the map.
           /<command> show TheDude - shows the player 'TheDude' from the map.
           /<command> render - Renders the tile at your location.
           /<command> fullrender - (Attempts to) render entire world from your location.
           /<command> fullrender world - (Attempts to) render entire world 'world'.
           /<command> radiusrender ## - (Attempts to) render at least ## block radius from your location.
           /<command> cancelrender - Cancels any active renders on current world
           /<command> cancelrender world - Cancels any active renders of world 'world'
           /<command> stats - Show render statistics.
           /<command> stats world - Show render statistics for maps on world 'world'.
           /<command> resetstats - Reset render statistics.
           /<command> resetstats world - Reset render statistics for maps on world 'world'.
permissions:
  dynmap.*:
    description: Gives access to all dynmap functions
    default: op
    children:
      dynmap.render: true
      dynmap.show.self: true
      dynmap.show.others: true
      dynmap.hide.self: true
      dynmap.hide.others: true
      dynmap.fullrender: true
      dynmap.radiusrender: true
      dynmap.cancelrender: true
      dynmap.reload: true
      dynmap.stats: true
      dynmap.resetstats: true
  dynmap.render:
    description: Allows /dynmap render command
    default: true
  dynmap.show.self:
    description: Allows /dynmap show (on self)
    default: true
  dynmap.show.others:
    description: Allows /dynmap show <player>
    default: op
  dynmap.hide.self:
    description: Allows /dynmap hide (on self)
    default: true
  dynmap.hide.others:
    description: Allows /dynmap hide <player>
    default: op
  dynmap.fullrender:
    description: Allows /dynmap fullrender or /dynmap fullrender <world>
    default: op
  dynmap.radiusrender:
    description: Allows /dynmap radiusrender
    default: op
  dynmap.cancelrender:
    description: Allows /dynmap cancelrender <world>
    default: op
  dynmap.reload:
    description: Allows /dynmap reload
    default: op
  dynmap.stats:
    description: Allows /dynmap stats or /dynmap stats <world>
    default: true
  dynmap.resetstats:
    description: Allows /dynmap resetstats or /dynmap resetstats <world>
    default: op
