name: dynmap
main: org.dynmap.DynmapPlugin
version: "0.20"
authors: [FrozenCow, mikeprimm, zeeZ]
softdepend: [Permissions]
commands:
  dynmap:
    description: Controls Dynmap.
    usage: |
           /<command> hide - hides the player from the map.
           /<command> hide TheDude - hides the player 'TheDude' from the map.
           /<command> show - shows the player from the map.
           /<command> show TheDude - shows the player 'TheDude' from the map.
           /<command> render - Renders the tile at your location.
           /<command> fullrender - (Attempts to) render entire world from your location.
           /<command> fullrender world - (Attempts to) render entire world 'world'.
           /<command> radiusrender ## - (Attempts to) render at least ## block radius from your location.
           /<command> cancelrender - Cancels any active renders on current world
           /<command> cancelrender world - Cancels any active renders of world 'world'
           /<command> stats - Show render statistics.
           /<command> stats world - Show render statistics for maps on world 'world'.
           /<command> resetstats - Reset render statistics.
           /<command> resetstats world - Reset render statistics for maps on world 'world'.
