rootProject.name = 'dynmap-forge'

include ':DynmapCoreAPI'
include ':DynmapCore'
include ':dynmap-api'
include ':forge-1.14.4'
include ':forge-1.15.2'
include ':forge-1.16.5'
include ':forge-1.17.1'
include ':forge-1.18.2'
include ':forge-1.19.3'
include ':forge-1.20.6'
include ':forge-1.21.6'
include ':forge-1.21.10'
include ':forge-1.21.11'

project(':DynmapCoreAPI').projectDir = "$rootDir/../DynmapCoreAPI" as File
project(':DynmapCore').projectDir = "$rootDir/../DynmapCore" as File
project(':dynmap-api').projectDir = "$rootDir/../dynmap-api" as File
project(':forge-1.14.4').projectDir = "$rootDir/../forge-1.14.4" as File
project(':forge-1.15.2').projectDir = "$rootDir/../forge-1.15.2" as File
project(':forge-1.16.5').projectDir = "$rootDir/../forge-1.16.5" as File
project(':forge-1.17.1').projectDir = "$rootDir/../forge-1.17.1" as File
project(':forge-1.18.2').projectDir = "$rootDir/../forge-1.18.2" as File
project(':forge-1.19.3').projectDir = "$rootDir/../forge-1.19.3" as File
project(':forge-1.20.6').projectDir = "$rootDir/../forge-1.20.6" as File
project(':forge-1.21.6').projectDir = "$rootDir/../forge-1.21.6" as File
project(':forge-1.21.10').projectDir = "$rootDir/../forge-1.21.10" as File
project(':forge-1.21.11').projectDir = "$rootDir/../forge-1.21.11" as File
